// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACE3ZgrViKWVedJVG5y9NkNdDdzuS4AQE',
    appId: '1:1075248763969:web:b68fe688d92a37e6dde2c0',
    messagingSenderId: '1075248763969',
    projectId: 'book-store-48bae',
    authDomain: 'book-store-48bae.firebaseapp.com',
    storageBucket: 'book-store-48bae.firebasestorage.app',
    measurementId: 'G-VL9DC5NSCB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfcrHvh3nEYiA0ioCjEm8M0O81e2gYykw',
    appId: '1:1075248763969:android:69064b87fe8e115cdde2c0',
    messagingSenderId: '1075248763969',
    projectId: 'book-store-48bae',
    storageBucket: 'book-store-48bae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ46EBrVc7HU9IMexDYEEmRMthc-wRNiA',
    appId: '1:1075248763969:ios:c1a9fd16d0f17e2cdde2c0',
    messagingSenderId: '1075248763969',
    projectId: 'book-store-48bae',
    storageBucket: 'book-store-48bae.firebasestorage.app',
    iosBundleId: 'com.example.bookStore',
  );
}
